name: Auto Merge PR

on:
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'merge')
      || (github.event_name == 'issue_comment' &&
          contains(github.event.comment.body, 'merge'))
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number || github.event.issue.number }}
          merge-method: squash
