name: Lint YAML Files

on:
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          path: .
          strict: true
